language: python
python:
- '2.7'
- '3.4'
install:
- pip install -r requirements.txt
- python setup.py install
script: nosetests
env:
  global:
    secure: TTffF3XTKjirIKMRLo6MLrEGqYWeXWwmKh1VlMym+Q1IjL38rx4wrSekxWx/zUDlEsKDHnAWOzlSGLO70omPIMnnY1ofRc5WPhRxyqq9CVPQp9mRLvr3dFxoVac0zf7BlwaPoI2n/kYHK6wxBpOocrolw5/IzTL5NBJrpv0WLQmtx5uYxA/YFvqDFEo38QLNjMWgOZZf3foZHIgC18QWXvQo9c1FUG1VJjsOj94zGGG1DxgLocQh3gIkhrhgDX1naAXkc/9GZX3IdH+Wrosz8f0u9qGNU7fOf9qfAv9h63+Mi0iIDGqOMAiaKpGVt83rEMhUxpdVUSOOtfSYyKtA1APJGkM0HuCsoB/YtNOYCF30xTMTWeUPIGAKKDaWqtWwyzVZ32eYRO6s5hMOjFr05tVl2WK2TgLVHjORzsUxUHqao54h64OreNvFKhEuVwiPaQw1Qjy9Ho/ozvM3XW1PD+98InIRK++BYiD5nH0xHXjhz0xzWwE7fLK8uwXcpAf8UcjhqsvQjrvEp2Hzm/PjzZOTPoIqKd+xDcfcGxyslFNwaLLojOfBpWF9ClaUqQfwwV8Ax+VbThCkY5INt9GjxTSbgc/59nV6oMi+4HCWO+ZIJRoeLbqNAHQpiLbNs89nBbv1Q/nPdL94QLSBuhs1mFFrNEEYLcfhgUlnv1jjtao=
