language: python
python:
- '2.7'
- '3.4'
install:
- pip install -r requirements.txt
- python setup.py install
script: nosetests
env:
  global:
  - secure: hrYv0btbdWJn2WlrJc/lnmKR75x5bMN4q7eft36/0ujQ3j2ClJ4Ka/F7bdtVuD/V24m20DEHypH1oynydo5JopT+0U2p/b83A6TPsKHKkLXp6lkXf8BnwxKt9TmCY5acWNlchSIyf52VkwbTHXLwrH7Z8iDwhWbKL9hkeCavjDYbNHiNlwe+zHe8/7HptciACRzPMDat6GlZAHWk1CskYM49MsI6rpC5C08SplJ/mhgNwQ8CStEjaX2Xjleubs4cu60baypvvtpApw5hwpWB9HO0gYvIZM23RmO51y16cNENq1iyiLtvQmtXyWkftTYlQhbbBvb3P0y0ytnZefp61utFlNWc757bHsf3ymXH2ScJ9IC7PCyXMTFhmWS7zxZOeFw/pFwyjhXonKBl1BjMkwTKqiCxWM5mOHLyLg4K7LDsw4sfS2eGv/EEsE8v8CC13a6acjIszObHXBsxovmJb91iZwEhKRo/ZNYf8d+Q+orltEvW4eJU0E1nP5zUHfv1qVMrLWp7o6ujWxDyTNeSFf2k5sdobG7hfYmVjb479ftdcjDncJus6Ju0ai2CLtVtgs7V/eu8IiAdHa4/hYnUSIDtSh6BkRvg0Ajx4lmgAWM+PvnOWR+jU+edyFQ5TWsQnHyFn20GTJKy2UgHgoLUqlcT+u9Aykqb4o1UViiBU2g=
  - secure: igwVj9Z3KMv0hbtfK89tsJyTXfsRE+m2q4TwmwfiKJogSFzmy0pH06ls9CQBKZj8WoWRYlnaXMQ8jlIask0G/jTax76iXuau83c3F+skmzm6c9h/LdVaFI7NlfdxAlTBlnt49qOArm/MJ+QYQgNYafUeH7j/DOxU02b2R1zbIy8M7CBbYwHtxwX7Ks5yPC6yZuFgefZXyudPQN/xfWqXEioLFxetpMd5N5RRt2qpoldnCiSqj77ego9mUfZWv3+23tFFEGIxtdoH8QtF1j69VQvOYhUISggyuIU+bVcWFq0IMUkLrPYUn0JV4U8lBjMmrYkii9sjSGHHsWiuok0Te6ng6KJERrmCa4E6Sbqoz471F0S3kF4goddn0N61CZk9e60DLgvjrt3mTzUTGuPrnYwXatXQl+jpCa9uak6vslMalyoOmLs4ynTcZutYtyhLJ37iUCpeDQfriSU754WzRYLYRohxshBYtbY0t4MAaJKwNdvPcYq7LzorfOY+sQ+47pLNSV2yzbSL+93ggP1y+YcvOFn7InMA4rkyUwDkmdw0QrCSfKlqcwyPba2vsUB91eUQx1XNFn2O/6Gh1Y/5yQcKX0NIbgGhwuJIz9M+Qevk//v4mrlNtqeB503l7+uRjpVAyOwXchpM5NMPgUIvlaCl1Vy4Lmb1WCvSH5thqEw=
