language: python
python:
- '2.7'
- '3.4'
install:
- pip install -r requirements.txt
- python setup.py install
script: nosetests
env:
  global:
  - secure: "Vz2Sy2RYr6kXD21hDw/1dWXb41REg/3AY1l7VIMV1Z3x1/8/+rsWbTS5tR+znFD+Jm3e2o3FX1Mx8oa2/MpgZZxAL/FNKoWMesQtykJq6fdXa7RzmXEAGBoYpEHvRoN3OJJiBFO+4Cf5U+XyfNFw/iRxzE34huOW5sSZfReywJKFW2qe0MiEtcy4VYLxWzLsNFZn3tyGVcybQydW/WPKptGTGNSi1uDxoDlam4UfDtW+fySx7GJo+IdmYIMX6Z22rANiAPhy2Q5ssIyfooFezpHb0930eKw5LUh6GiQevMqJHGwUkdhKUIOfVKQAdNGf+aV9qKYNt5D8yr+lW8xjob4bZxKzil9NzUMfJ7k3b6WMam0qLrw1rXUAgV6WGOyO7hAcoBsTJDT9eeygdmuPavOODYBh2V8UE35ZkdOI/+eY41DOPh6SwUyocgi5MJ+BGG8ebiIuIP5LW2kNTxPzGwy7zI1uA4CrFvBTaLK9FTkkYM6+qfN0VMOi3DgjJtklbiXgNwEbDHmU9NaO4VDlceY+QUO4H9/p52RbY4XdkpC1gmsNdLJJ3SNC4J+Dy+boE1uPhREFbDJxo6tuhJWD/m87ljl/eYYbaKf3FaeLhFbncwb02Wsec3A1NJ08Q1jRUE2E4SPRq15Jt4iGUQL5tSgSc5CEYxR3oFuisHETJIg="
  - secure: "NBtyDeeCG90o8VJL36Bda7tc0t86PboFkTB/T2ciLH8GE7mvgrcY4a6BwoTIEpD4EJZlqP26wsmjt7KRuox6BifDvYqlbwh2bPrZm/JJ6crKetm3fL4sSV8lxvKkRIq9wqVZCh1WSmvA7K3ydpVqwVZM74wcF7tYhgih2ml/LuwxXrqEOhMFnI5b5OoLI7NSX/5N/+ix6OLn7LJeOYI0sZ8eaxjUgOFlT0MRfukDD8wWPHUJ3CfeTFNW/LQG/AqeJyqoe/KfbpcmZLRv1fM44CXLkZdGWhsmJn64TLQ5F0IONHdfiahxpvGOV9w0eouxHT/ppf+WI+WTrJQsulIMo3GoLm27O8qyKMR3KG4+CMdtAjQUOoPKXwQDHW/i6ayAoUQoowRTOOYXeT3h3tm3lYsZHOJomByMMo7Pho4V8V9gFdmHywP1N+msdy+bv/BJm88nsnalfqmaorvCnNlVjVwiehMP4UXP8WyAuHLICeihrjtL3Et0MR7122iFk/tLfDhDjegIRn93v72HX/AU0qXM1kxZWDV0qEefvacSo8E3HTuylWotuwhtkHmkpg62D3OFE2V3KqnOg0merQjbmmSqi+SKY/rN3NASeek5qVShIt4zoe77Cib7QguigSg471TT35/JrE9rKtccnlLYG4WsvCgx80LUodBjmpYAMlc="
